/**
 * Created by pzl on 16/8/21.
 */
var ReactNative = require('react-native');
var Dimensions = require('Dimensions');
var {
    StyleSheet,
    PixelRatio
    } = ReactNative;
console.log(PixelRatio.get()/3);
export default findStyles = StyleSheet.create({
    findView: {
        flex: 1,
        backgroundColor:'#eeeeee',
        marginTop:-20
        //alignItems: 'center',
        //justifyContent:'center'
    },
    bannerTop: {
        flex:1,
        height:368,
        position:'relative'
    },
    bannerTopImage:{
        flex:1,
        height:368,
        width:Dimensions.get('window').width,
        position:'relative',
    },
    changeCity:{
        position:'absolute',
        left:10,
        top:20,
        width:80,
        height:35,
        borderRadius:2,
        overflow:'hidden',
        justifyContent:'center',
        borderWidth:1,
        borderColor:"#fff",
    },
    changeCityText:{
        textAlign:'center',
        color:"#fff"
    },
    bannerText:{
        position:'absolute',
        top:184,
        flex:1,
        fontSize:18*(PixelRatio.get()/3),
        width:Dimensions.get('window').width,
        backgroundColor:'transparent',
        color:'#fff',
        //alignItems: 'center',
        textAlign:'center',
        //justifyContent:'center'
    },
    bannerButtonBig:{
        flex:1,
        position:'absolute',
        bottom:15,
    },
    bannerButtonBigOne:{
        width:Dimensions.get('window').width,
        position:'relative',
        alignItems:'center'
    },
    bannerButtonBigTwo:{
        width:332*(PixelRatio.get()/3),
        height:45,
        borderWidth:1,
        borderColor:'#fff',
        borderRadius:2,
        backgroundColor:'rgba(255,255,255,0.3)',
        alignItems:'center',
        justifyContent:'center'
    },
    bannerButtonBigImage:{

    },
    bannerButtonBigText:{
        color:"#fff",
        fontSize:18
    },
    slide:{
        padding:10,
        marginTop:15,
        backgroundColor:"#fff"
    },
    slideListView:{
       marginTop:10
    },
    slideText:{
        textAlign:'center',
        fontSize:16,
        lineHeight:25
    },
    slideTouch:{
        width:165*(PixelRatio.get()/3),
        height:110*(PixelRatio.get()/3),
        marginRight:10,
        backgroundColor:'#ddd',
        position:'relative'
    },
    slideImage:{
        width:165*(PixelRatio.get()/3),
        height:110*(PixelRatio.get()/3),
        marginRight:10,
        backgroundColor:'#00ff00'
    },
    slideTouchCode:{
        position:'absolute',
        right:10,
        bottom:10,
        width:50*(PixelRatio.get()/3),
        height:25,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'rgba(0,0,0,0.7)'
    },
    slideTouchCodeText:{
        color:'#fff'
    },
    todayRecommend:{
        marginTop:15,
        backgroundColor:'#fff',
        paddingTop:10
        //borderTopColor:'#ddd',
        //borderTopWidth:15
    },
    todayRecommendTitle:{
        textAlign:'center',
        height:32,
        lineHeight:25,
        fontSize:18,
    },
    todayRecommendLi:{
        width:Dimensions.get('window').width,
        //height:308,
        backgroundColor:'#f5f5f5',
        position:'relative'
    },
    todayRecommendLiBanner:{
        height:276*(PixelRatio.get()/3),
        backgroundColor:'rgba(0,0,0,0.5)'
    },
    todayRecommendLiImg:{
        position:'absolute',
        left:0,
        top:0,
        height:276*(PixelRatio.get()/3)
    },
    todayRecommendLiPrice:{
        position:'absolute',
        left:0,
        bottom:45,
        width:88,
        height:28,
        backgroundColor:'#313131',
        textAlign:'center',
        lineHeight:22,
        justifyContent:'center',
        color:'#fff'
    },
    todayRecommendLiImgCodeList:{
        position:'absolute',
        left:10,
        bottom:10
    },
    todayRecommendLiImgCode:{
        height:25,
        paddingLeft:10,
        paddingRight:10,
        backgroundColor:'rgba(0,0,0,0.1)',
        borderWidth:1,
        borderColor:'#fff',
        lineHeight:19,
        color:'#fff',
        marginRight:10,
    },
    todayRecommendLiDes:{
        padding:10,
        backgroundColor:'#fff'
    },
    todayRecommendLiDesTitle:{
        marginBottom:5,
        fontSize:18
    },
    todayRecommendLiDesCodeList:{

    },
    todayRecommendLiDesCode:{
        marginRight:25
    },
    RecommendLike:{
        position:'absolute',
        right:10,
        top:276*(PixelRatio.get()/3)-20,
        width:40,
        height:40,
        borderRadius:20,
        backgroundColor:'#fff',
        borderWidth:1,
        borderColor:'#f5f5f5',
        alignItems:'center'
    },
    likeView:{
        marginTop:15,
        backgroundColor:'#fff',
        paddingTop:5
    },
    likeTitle:{
        textAlign:'center',
        height:32,
        lineHeight:25,
        fontSize:18
    },
    likeLi:{
        borderBottomWidth:1,
        borderBottomColor:'#f5f5f5',
        paddingTop:10,
        paddingBottom:10
    },
    likeImg:{
        width:125,
        height:125*2/3,
        backgroundColor:'#eee',

    },
    likeLiView:{
        paddingLeft:5,
        width:Dimensions.get('window').width-130
    },
    likeLiTitle:{
        fontSize:16,
        lineHeight:25,
        color:'#333333'
    },
    likeLiAddress:{
        fontSize:13,
        lineHeight:24,
        color:'#666'
    },
    likeCodeLi:{
        marginTop:5
    },
    likeCode:{
        paddingLeft:10,
        paddingRight:10,
        marginRight:5,
        fontSize:10,
        height:20,
        lineHeight:15,
        borderWidth:1,
        color:'#666',
        borderColor:'#cccccc'
    }


});